/*

Leetcode Problem 389: Find the Difference (Easy)

You are given two strings s and t.
String t is generated by random shuffling string s and then add one more letter at a random position.
Return the letter that was added to t.

Complexity for this solution:
O(n ) time (n length of s) and constant space (only 26 characters)

*/

public class FindTheDifference {

    // count how many times characters occur in s, then substract the occurrences in t
    // the additinal character has a negative count after that
    public static char findTheDifference(String s, String t) {
        int[] counts = new int[26];

        for (char ch : s.toCharArray()) {
            counts[ch - 'a']++;
        }

        for (char ch : t.toCharArray()) {
            counts[ch - 'a']--;
            if (counts[ch - 'a'] < 0)
                return ch;
        }

        // nothing found
        return ' ';

    }

    public static void main(String[] args) {
        String s = "abced";
        String t = "dcebba";
        System.out.println(findTheDifference(s, t));
    }
}
